name: "Conform Action, Jira enabled. POC"
description: "Policy enforcement for your pipelines, Jira enabled. POC"
branding:
  icon: "check-circle"
  color: "gray-dark"
inputs:
  token:
    description: "The GitHub token. Must have repo:status access. Can be specified by using {{ secrets.GITHUB_TOKEN }}"
    required: true
runs:
  using: "docker"
  image: "docker://morganwattiez/conform:latest"
